name: Feature request
description: Propose an improvement or new capability
labels: [enhancement, needs-triage]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user problem are we solving?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the behavior and API/UI impact.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered

  - type: textarea
    id: impact
    attributes:
      label: Scope and impact
      description: Risks, migration concerns, affected areas.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight checks
      options:
        - label: I searched existing issues and discussions.
          required: true
        - label: I am willing to open a PR for this.
          required: false
